# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-01-04 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, choices=[('ai', 'ai'), ('python', 'python'), ('linux', 'linux')], max_length=10, null=True),
        ),
    ]
